Repository sendgrid/dx-automator, pull requests merged in 2018-11, with the labels that each got.

#52 Fix GraphQL pagination issue
  scripts/README.md
  services/github/project/api/views.py
Labels: difficulty: medium, status: code review request, status: ready for deploy, type: bug

#53 Fixed issue with parsing usernames with a dash
  services/github/project/api/views.py
Labels: difficulty: easy, status: code review request, status: ready for deploy, type: bug

#54 GitHub service get all open prs
  README.md
  services/github/project/api/views.py
  services/github/project/tests/test_github.py
Labels: difficulty: medium, status: ready for deploy, type: sendgrid enhancement

#55 Hacktoberfest 2018
  examples/hacktoberfest_example.py
  services/github/project/api/views.py
Labels: status: code review request

#51 removed unused python modules
  services/looker/main.py
  services/looker/project/api/routes.py
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved, type: community enhancement
