Repository sendgrid/dx-automator, pull requests merged in 2018-10, with the labels that each got.

#29 Fixed broken link to development branch
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#37 Adding first timers file
  FIRST_TIMERS.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#41 PEP8 Updated
  services/github/manage.py
  services/github/project/__init__.py
  services/github/project/api/views.py
  services/github/project/config.py
  services/github/project/tests/base.py
  services/github/project/tests/test_config.py
  services/github/project/tests/test_github.py
  services/tasks/manage.py
  services/tasks/project/__init__.py
  services/tasks/project/api/__init__.py
  services/tasks/project/api/models.py
  services/tasks/project/api/tasks.py
  services/tasks/project/tests/base.py
  services/tasks/project/tests/test_config.py
  services/tasks/project/tests/test_tasks.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#48 Use COPY instead of ADD in Dockerfile
  services/github/Dockerfile
  services/github/nginx/Dockerfile
  services/looker/project/db_creation/Dockerfile
  services/tasks/project/db/Dockerfile
  services/users/project/db/Dockerfile
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#50 https://github.com/sendgrid/dx-automator/issues/49
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#45 Migrate to Github API v4
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  services/github/project/api/views.py
  services/github/project/config.py
  services/github/project/tests/test_config.py
  services/github/project/tests/test_github.py
  services/github/requirements.txt
  source_the_things.sh
Labels: difficulty: hard, hacktoberfest, status: code review request, status: hacktoberfest approved, type: sendgrid enhancement
