Repository sendgrid/dx-automator, pull requests merged in 2018-09, with the labels that each got.

#23 Looker service
  docker-compose-dev.yml
  services/looker/Dockerfile
  services/looker/Dockerfile-prod
  services/looker/README.md
  services/looker/docker-compose-dev.yml
  services/looker/docker-compose-prod.yml
  services/looker/entrypoint-prod.sh
  services/looker/entrypoint.sh
  services/looker/main.py
  services/looker/nginx/Dockerfile
  services/looker/nginx/prod.conf
  services/looker/project/__init__.py
  services/looker/project/api/__init__.py
  services/looker/project/api/db_cache.py
  services/looker/project/api/dx_looker_service.py
  services/looker/project/api/json_cleaner.py
  services/looker/project/api/looker_api_handler.py
  services/looker/project/api/models.py
  services/looker/project/api/routes.py
  services/looker/project/config.py
  services/looker/project/db_creation/Dockerfile
  services/looker/project/db_creation/column_transformations.json
  services/looker/project/db_creation/create.sql
  services/looker/project/tests/__init__.py
  services/looker/project/tests/base.py
  services/looker/project/tests/test_config.py
  services/looker/project/tests/test_dx_looker.py
  services/looker/requirements.txt
Labels: difficulty: hard, status: waiting for feedback, type: sendgrid enhancement

#26 Added helpful scripts for user friendly execution
  scripts/README.md
  scripts/run-local-react-client
  scripts/setup-local-db
  scripts/stop-local-react-client
  services/client-react/README.md
Labels: status: code review request, type: community enhancement, type: docs update, type: getting started

#27 Fixed docker errors
  docker-compose-dev.yml
  scripts/README.md
  scripts/run-local-react-client
  scripts/setup-local-db
  scripts/stop-local-react-client
  setup_db
Labels: status: code review request
