Repository sendgrid/dx-automator, pull requests merged in 2019-04, with the labels that each got.

#66 Security updates
  services/github/requirements.txt
  services/hacktoberfest/requirements.txt
  services/looker/requirements.txt
Labels: difficulty: easy, status: code review request, status: ready for deploy, type: security

#44 Fix CLI option command naming
  README.md
  services/looker/README.md
  source_the_things.sh
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: sendgrid enhancement

#39 Detail Gitflow Workflow
  .github/PULL_REQUEST_TEMPLATE
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: docs update

#33 WIP: Run code through style guide checks
  services/looker/requirements.txt
  services/tasks/project/__init__.py
  services/tasks/project/api/models.py
  services/tasks/project/api/tasks.py
  services/tasks/project/config.py
  services/tasks/requirements.txt
  services/tasks/setup.cfg
  services/users/requirements.txt
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: sendgrid enhancement

#67 Add example for security issues
  README.md
  examples/open_security_issues.py
Labels: difficulty: easy, status: code review request, status: ready for deploy, type: docs update

#68 Created Triage Page
  docker-compose-dev.yml
  services/client-react/docker-compose-dev.yml
  services/client-react/package-lock.json
  services/client-react/package.json
  services/client-react/src/App.jsx
  services/client-react/src/components/IssuesList.jsx
  services/client-react/src/index.css
  services/github/project/api/views.py
Labels: status: code review request
