Repository sendgrid/dx-automator, pull requests merged in 2019-05, with the labels that each got.

#70 Populate Tasks DB with all open GitHub Issues and PRs
  .gitignore
  README.md
  docker-compose-dev.yml
  scripts/init-task-db
  services/github/project/api/views.py
  services/tasks/manage.py
  services/tasks/project/api/models.py
  services/tasks/project/api/tasks.py
  services/tasks/requirements.txt
  services/users/manage.py
Labels: difficulty: hard, status: ready for deploy, type: sendgrid enhancement

#71 Triage and follow up script update
  examples/follow_up.py
  services/client-react/src/App.jsx
  services/client-react/src/index.css
  services/tasks/manage.py
Labels: status: code review request

#72 Fix followups
  README.md
  examples/code_review.py
  examples/follow_up.py
  examples/hacktoberfest_example.py
  examples/open_bugs.py
  examples/open_security_issues.py
  examples/unlabeled_issues.py
  services/client-react/src/App.jsx
  services/github/README.md
  services/github/project/__init__.py
  services/github/project/api/graphql.py
  services/github/project/api/routes.py
  services/github/project/api/views.py
  services/github/project/tests/test_graphql.py
  services/tasks/project/api/models.py
  services/tasks/project/api/tasks.py
  services/tasks/project/tests/test_tasks.py
Labels: difficulty: hard, status: code review request, type: sendgrid enhancement

#73 Fix tasks service for new GitHub service interface
  services/nginx/flask.conf
  services/tasks/project/__init__.py
  services/tasks/project/api/routes.py
  services/tasks/project/config.py
Labels: difficulty: easy, status: code review request, type: bug

#74 Support for RICE prioritization
  examples/.env_sample
  examples/README.md
  examples/calculate_rice_score.py
  services/github/project/api/graphql.py
  services/github/project/api/routes.py
  services/github/project/tests/test_graphql.py
  services/hacktoberfest/project/__init__.py
  services/hacktoberfest/project/api/routes.py
  services/hacktoberfest/project/config.py
  services/tasks/project/api/models.py
  services/tasks/project/api/priority.py
  services/tasks/project/api/routes.py
  services/tasks/project/config.py
  services/tasks/project/tests/test_tasks.py
  services/tasks/requirements.txt
  services/users/project/api/users.py
  services/users/project/config.py
Labels: difficulty: medium, status: code review request, type: sendgrid enhancement

#75 Get a list of RICE sorted issues and PRs
  README.md
  examples/rice_sorted_list_of_issues_and_prs.py
  examples/update_rice_scores.py
  services/github/project/api/routes.py
  services/tasks/project/api/routes.py
  services/tasks/project/tests/test_tasks.py
Labels: difficulty: medium, status: code review request, type: sendgrid enhancement
